### ISSUE TITLE
procedure TKCustomGrid.InternalUnlockUpdate;

### ISSUE THREAD

**Issue by kryslt** [kryslt/KControls#10]
**[Original report](https://bitbucket.org/tomkrysl/kcontrols/issue/10) by liuzg2 (Bitbucket: [liuzg2](https://bitbucket.org/liuzg2), GitHub: [liuzg2](https://github.com/liuzg2)).**

----------------------------------------

procedure TKCustomGrid.InternalUnlockUpdate;  
begin  
ClearSortMode;  
// ValidateInitialPositions; ---------《《《《《《《 will too slow when end update  
UpdateAxes\(True, cAll, True, cAll, \[afCheckMinExtent\]\);  
end;

**Comment by kryslt** [comment]
Finally I've found how to transfer issues from Bitbucket to Github, no need for you to create new issue for this.

**Comment by kryslt** [comment]
This could only happen when there are many columns or rows in the grid. 
How many do you have?

**Comment by liuzg2** [comment]
may be  100000

**Comment by kryslt** [comment]
Ok, I've checked this now and can confirm the problem.
It is related to #19.
is not just the slowness of InternalUnlockUpdate but there are many other issues bound to such huge numbers of rows/columns.
Selections are slow etc.
KGrid was not originally built for such huge amounts of rows or columns.
Maybe this will be fixed sometimes in the future but do not hope for it.
Reasonable amounts are about 10000 rows maximum.
Use another solution if you need such huge numbers of rows.
I keep this issue open just for case.

**Comment by kryslt** [comment]
I finally fixed this by making ValidateInitialPositions public, to be called explicitly when needed.
When manipulating columns/rows only with the TKGrid functions (adding, deleting, moving) there should be no need to call this method.
