### ISSUE TITLE
can you add a foot panl for kgrid

### ISSUE THREAD

**Issue by kryslt** [kryslt/KControls#11]
**[Original report](https://bitbucket.org/tomkrysl/kcontrols/issue/11) by liuzg2 (Bitbucket: [liuzg2](https://bitbucket.org/liuzg2), GitHub: [liuzg2](https://github.com/liuzg2)).**

----------------------------------------

can you add a foot panl for kgrid

**Comment by kryslt** [comment]
Finally I've found how to transfer issues from Bitbucket to Github, no need for you to create new issue for this.

**Comment by kryslt** [comment]
I know what you mean but this is too much work with this. 
If you can provide a patch it would be great because I have no time to implement this now.

**Comment by liuzg2** [comment]
i am not  a good  programmer  ,  mm  ..  i has added somthing  ,but  not good   
1、add  a panl  for foot
2、Support   rows=1 and fixrows=1  
.....
[KGrids.zip](https://github.com/kryslt/KControls/files/4062683/KGrids.zip)

**Comment by kryslt** [comment]
No suitable patch included, closing this issue.
