### ISSUE TITLE
add somthing

### ISSUE THREAD

**Issue by kryslt** [kryslt/KControls#12]
**[Original report](https://bitbucket.org/tomkrysl/kcontrols/issue/12) by liuzg2 (Bitbucket: [liuzg2](https://bitbucket.org/liuzg2), GitHub: [liuzg2](https://github.com/liuzg2)).**

----------------------------------------

function TKCustomGrid.InternalMove

end;  
mcRight:  
begin  
Inc\(ACol\);

```
       while ACol< FColCount  do       <<<<<   i  add   this    jump over  when reaonly
          begin
            if   Cols[ACol].ReadOnly then

              Inc(ACol)
              else Break;
          end;
    if ACol < FColCount then
    begin
      if FMemRow >= 0 then
        ARow := FMemRow;
      FMemCol := ACol;
    end
```

‌

‌

i add this  to draw  mod row color

procedure TKGridCellPainter.Drawmodrows;  
begin

```
 if   (State * [gdFixed, gdSelected] = []) and (FRow>=0)  then
```

begin  
if FRow mod 2 = 0 then  
Canvas.Brush.Color := self.FGrid.Color  
else  
Canvas.Brush.Color := RGB\(240,240,255\);  
end;

end;

**Comment by kryslt** [comment]
Finally I've found how to transfer issues from Bitbucket to Github, no need for you to create new issue for this.

**Comment by kryslt** [comment]
Please generate patch for this. And replace `Canvas.Brush.Color := RGB(240,240,255);` with some generous solution (extra published color property etc.).

**Comment by liuzg2** [comment]
i do not know how to patch   ,but i have upload a  file   in another  issues

**Comment by kryslt** [comment]
No suitable patch included, closing this issue.
