### ISSUE TITLE
JOSN file needs update (or refocus)

### ISSUE THREAD

**Issue by davidbannon** [kryslt/KControls#17]
TK, the josn file used for Lazarus Online Package Manager points to a year old  https://github.com/kryslt/KControls/archive/1.7.3.zip file.  I am not sure you wan to be involved in gererating a new one of those on each commit. Further, as the version is no longer being inc, it probably does not make sense.

Github kindly makes a new master.zip on every commit for you, maybe changing the Download URL to  https://github.com/kryslt/KControls/archive/master.zip is appropriate ?

Davo

**Comment by kryslt** [comment]
Since I am still very busy with other things and dont have time to resume real work on these components it is probably the best idea. I commited a fix and only hope the OPM will know how to handle this "master" version.
