### ISSUE TITLE
take a long time for set rowcount

### ISSUE THREAD

**Issue by liuzg2** [kryslt/KControls#19]
grid.rowcount:=200000  
will take a longtime  

procedure TKCustomGrid.ChangeDataSize(ColInsert: Boolean; ColAt, ColCnt: Integer;
  RowInsert: Boolean; RowAt, RowCnt: Integer);

  procedure Axis(var Data: TKGridAxisItems;
    Insert: Boolean; DefFixedCnt: Integer; var At, Cnt, MaxLen, ItemCount, FixedCount: Integer);
  var
    I, Len: Integer;
    Item: TKGridAxisItem;
  begin
    FlagSet(cGF_GridUpdates);
    try
      if Cnt > 0 then
      begin
        Len := Data.Count;
        if Insert then
        begin
          At := MinMax(At, 0, Len);
          for I := At to At + Cnt - 1 do
          begin
            Item := Data.InsertOnly(I);
            Item.Grid := Self;
            Item.InitialPos := MaxLen + 1;
            Inc(MaxLen);
          end;

**Comment by liuzg2** [comment]
maybe     do not  create  TKGridRow  object  when set  rowcount

**Comment by kryslt** [comment]
Will be fixed in a different way.

**Comment by kryslt** [comment]
I've checked this now and can confirm the problem.
It is not just the row creation but there are many other issues bound to such huge numbers of rows/columns. 
Selections are slow etc.
KGrid was not originally built for such huge amounts of rows or columns.
Maybe this will be fixed sometimes in the future but do not hope for it.
Reasonable amounts are about 10000 rows maximum.
Use another solution if you need such huge numbers of rows.
I keep this issue open just for case.

**Comment by kryslt** [comment]
Has been fixed in 1dcbcd5 and ea06ff4. There were many issues causing this mainly because of the grid complexity, eg. a slow calculation of range selection to be painted.
