### ISSUE TITLE
Enhancement: Row select, Column select or All select and cell focus...

### ISSUE THREAD

**Issue by AzzaAzza69** [kryslt/KControls#22]
Like Excel, I think that row select should focus the first visible column, col select should focus the first visible row, and All select should do both

**Comment by kryslt** [comment]
There is only row selection possible in KGrid. And I am not sure this is a good idea to change the behavior this way by default. Instead, use FocusCell to focus the respective first visible cell (given by TopRow or LeftCol) whenever you need.

**Comment by AzzaAzza69** [comment]
By row/col select, I meant the range selection...

**Comment by kryslt** [comment]
Ok, first, KGrid is not Excel and it is not its aim to emulate it.
There is range selection with different styles, see RangeSelectStyle. 
Excel has some other range selection styles.
I guess you mean that clicking on fixed cells (Excel selects entire row/column and focuses first visible cell in the range).
If so then this is not supported and not easy to implement.
KGrid cannot place the focused cell in the middle of the selected range.
Use some different solution (like some spreadsheet component) if you need this feature.
Or just use some custom cell drawing and mouse handling for that.

**Comment by kryslt** [comment]
Closing this, cannot be made.
