### ISSUE TITLE
Warning: other unit files search...

### ISSUE THREAD

**Issue by hoyosfelix** [kryslt/KControls#25]
Hello,

I downloaded and installed the last versión 1.7.3 on Windows 10 and Lazarus 2.0.4.

When I try to  compile a project shows 2 warnings:

```
Ventana de Mensajes, Advertencias: 2
Warning: other unit files search path (aka unit path) of "KControlsLaz 1.7.3" contains "C:\lazarus204_32\components\KControls-1.7.3\source", which belongs to package "KControlsBase"

Warning: other unit files search path (aka unit path) of "KControlsBase 1.7.3" contains "C:\lazarus204_32\components\KControls-1.7.3\source", which belongs to package "KControlsLaz"
```
Please help me to solve this issue.

Thanks in advance.

**Comment by kryslt** [comment]
This is IMO a Lazarus bug.
https://forum.lazarus.freepascal.org/index.php?topic=34822.0
Maybe I report this issue to Lazarus bugtracker some day...
