### ISSUE TITLE
Please warn about the license

### ISSUE THREAD

**Issue by davidbannon** [kryslt/KControls#29]
Hi TK, given the content in https://github.com/kryslt/KControls/issues/27 can I respectfully suggest that a clear statement be made in this repository's README.md, under the License section, to the effect that KControls has been determined to have a license that is not suitable for inclusion in the Debian repositories.

It would be good to prevent people from making the mistake I made, quite a lot of unproductive effort !  The Debian test is the gold standard for anything claiming to be open source, without their stamp of approval, my application is going nowhere. Sigh ...

Thanks anyway !

Davo

**Comment by kryslt** [comment]
This will be fixed by a licensing change, see #27. Closing this issue now...

**Comment by davidbannon** [comment]
Thanks heaps for fixing this TK.  Its now likely I will get tomboy-ng into Debian.  If I do, will let you know.

Davo

**Comment by kryslt** [comment]
Thank you. If you don't, please reopen #27 instead of creating new issue.

**Comment by davidbannon** [comment]
No, I cannot reopen an issue you have closed, even it was initially opened by me.
But never mind, if I have further problems with Debian, it will be my fault, not yours, you have done everything they asked !
Davi

**Comment by kryslt** [comment]
Ah didn't know that, sorry. Then in case of further problems, create a new issue.
