### ISSUE TITLE
Package for Delphi 11 Alexandria?

### ISSUE THREAD

**Issue by PeterPanino** [kryslt/KControls#39]
Could you please add an explicit package for Delphi 11 Alexandria? Thank you!

**Comment by PeterPanino** [comment]
When trying to install KControls_D10_2.dproj in Delphi 11.1 Alexandria, I got this error message:

[dcc32 Error] kedits.pas(949): E2010 Incompatible types: 'Integer' and 'SmallInt'

**Comment by PeterPanino** [comment]
**kcontrols.inc** needs an update for Compiler **VER350**.

**Comment by kryslt** [comment]
Support for new Delphi versions will not be added anymore.
If you need this please add this yourself and create a pull request.
Like this one https://github.com/kryslt/KControls/pull/30.

**Comment by kryslt** [comment]
They were finally added because of many user requests.
