### ISSUE TITLE
KGrid AEditor as TButton always visible

### ISSUE THREAD

**Issue by awunnenb** [kryslt/KControls#41]
How can i create an always visible AEditor as TButton with Caption and ClickEvent for each row (Delete Button)

**Comment by kryslt** [comment]
The only way is drawing button frame in the cells and then create a working TButton in OnEditorCreate.
Example for a graphic button frame:
```
procedure TForm.TKGridDrawCell(Sender: TObject; ACol, ARow: Integer;
  R: TRect; State: TKGridDrawState);
var
  G: TKGrid;
  Bounds, Interior: TRect;
begin
  G := Sender As TKGrid;
  G.CellPainter.Graphic := FGraphic; // some typical graphic for a close button
  G.CellPainter.DrawDefaultCellBackground;
  G.CellPainter.DrawButtonFrame(R);
  G.CellPainter.CellGraphicRect(R, Bounds, Interior, stmNone);
  G.CellPainter.DrawCellGraphic(Bounds, Interior);
end;

```

This is not a bug report but a question.
This does not belong here!
Just in case, I'm leaving this issue open...
