### ISSUE TITLE
KGrid: when get focus again, selected rows are not repainted

### ISSUE THREAD

**Issue by DomenicoMammola** [kryslt/KControls#45]
Hi,
if you
1. add goRowSelect and goRangeSelect to the grid Options
2. select two or more rows
3. show a new form in front of the grid so that the grid would lose focus
4. close the form so that the grid would get again focus
5. only the current row is repainted correctly, the other rows are mispainted

Last version of KControls master branch, Windows 10.

This is a small recording of what happens:

![KGRID](https://github.com/kryslt/KControls/assets/3284795/7707a202-c8e2-4b55-8a18-574b0dab9f67)

I think that there is a problem in the InvalidateCurrentSelection procedure. I will post a patch as pull request to be validated.
TIA,
Domenico

**Comment by kryslt** [comment]
Fixed by the reporter, closing issue...

**Comment by kryslt** [comment]
The reported fixed this badly, see #47.
