### ISSUE TITLE
KGrid: under particular circumstances, old selected row is still painted as selected even if selection is changed

### ISSUE THREAD

**Issue by DomenicoMammola** [kryslt/KControls#47]
Hi,

1. create a KGrid with goVirtualGrid and goRowSelect and goRangeSelect in Options with 2 rows and 1 fixed row
2. first row is automatically selected
3. add a row to the grid
4. click on the new row to select it
5. first old row is still painted as focused/selected even if it's not

Last version of KControls from master, Windows 10, Lazarus 2.2.6

![KGRID_2](https://github.com/kryslt/KControls/assets/3284795/7f4ac7de-416f-4e7b-be2e-ae43d8333655)

[kgrid_test_project.zip](https://github.com/kryslt/KControls/files/13040315/kgrid_test_project.zip)

TIA,
Domenico

**Comment by kryslt** [comment]
Caused by a bad fix of #45.
