### ISSUE TITLE
Unable to reduce selection with CTRL + mouse click

### ISSUE THREAD

**Issue by DomenicoMammola** [kryslt/KControls#49]
Hi,
if you enable multiselection and rowselection and  in a TKGrid then you can select multiple rows with CTRL + mouse click but you can't remove a row from the selection by clicking again on a previously selected row (with CTRL pressed).
In other words with CTRL you can only add a new row to the current selection but you can't remove any of them. Most grids allow to add and remove rows just by multiple clicks with CTRL pressed.
Is this the desiderated behaviour? Am I missing anything in the options?
Thanks!
Domenico

PS
Do you need a test project?

**Comment by kryslt** [comment]
Which grids? Eg. MS Excel does not support this. I've made this similar to MS Excel.

**Comment by DomenicoMammola** [comment]
Hi, I'm sorry if I was not able to correctly explain myself. I was talking about how to change dinamically selected rows by clicking with mouse left button and CTRL pressed. If I've selected a bunch of grid rows with CTRL+mouse click, then I'm not able to de-select one or more by clicking again on them while keeping the others selected (please note that CTRL was kept pressed while clicking with the mouse):

![PowerToys_yMbNN8nu7D](https://github.com/kryslt/KControls/assets/3284795/dfea1820-8108-43be-9710-24f86994adca)

Is there any way to obtain this? Am I missing something?
TIA,
Domenico

**Comment by kryslt** [comment]
I see. It is already there but broken. I'll see what can be done.

**Comment by kryslt** [comment]
Has been fixed in d2eab0d. The feature was partially there (and broken, did not work), partially not. Now you are able to add/remove both rows and columns by clicking on fixed cells. Needs both gxFixedCellClickSelect and gxFixedCellClickToggle options to be checked.
