### ISSUE TITLE
Error compiling KControls in Delphi 12

### ISSUE THREAD

**Issue by CommEx256** [kryslt/KControls#53]
Error compiling KControls in Delphi 12 (Version 29.0.50491.5718)
[dcc32 Error] kedits.pas(949): E2010 Incompatible types: 'Integer' and 'SmallInt'
[dcc32 Fatal Error] F2063 Could not compile used unit 'kedits.pas'

949 FUpDown.OnChangingEx := UpDownChangingEx;

What could be the matter?

**Comment by kryslt** [comment]
Reason is missing compiler defines for Delphi 10 Rio to 12.
