### ISSUE TITLE
KMemo: adding the string ")" after the paragraph letter

### ISSUE THREAD

**Issue by kryslt** [kryslt/KControls#61]
### Discussed in https://github.com/kryslt/KControls/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **radekjindra** July 25, 2024</sup>
Hello, I would like to ask for advice. I need to add the line ")" after the paragraph letter. a) b) c)

I have for now

TB:=Protokol_ZKP.Blocks.AddTextBlock('Non-metallic materials for line conductors are preferred over metallic ones with insulating contacts.');
TB.TextStyle.Font.Name:='Times New Roman';
TB.TextStyle.Font.Color:=clRed;
TB.TextStyle.Font.Style:=[fsBold];
TB.TextStyle.Font.Size:=10;
PA:=Protokol_ZKP.Blocks.AddParagraph;
PA.ParaStyle.NumberingListLevel := 0;
PA.Numbering := pnuLetterLo;
PA.ParaStyle.HAlign:=halJustify;
PA.NumberingListLevel.FirstIndent:=10;
PA.NumberingListLevel.LeftIndent :=30;
PA.ParaStyle.NumberStartAt := 1; 

</div>

**Comment by radekjindra** [comment]
Thank you for your advice

**Comment by radekjindra** [comment]
I would like to ask you for an example, thank you very much.
