### ISSUE TITLE
TKMemo: Can't show GIF Image.

### ISSUE THREAD

**Issue by bird00101011** [kryslt/KControls#63]
![image](https://github.com/user-attachments/assets/b23560ba-4ec7-41c2-b112-d68b08208470)

Hello, guys, my app can't show GIF image. How to fix it.

**Comment by kryslt** [comment]
What compiler and component?

**Comment by bird00101011** [comment]
![image](https://github.com/user-attachments/assets/8df8e0c6-0524-4ff5-8095-376faff80d90)

The newest Lazarus IDE, fpc version is "fixes-3.2", kmemo component.

**Comment by kryslt** [comment]
Can you attach the image that is not working?

**Comment by kryslt** [comment]
Ok found out an issue with Delphi TGifImage, the image did not display because no alpha channel was copied. Maybe this also helps in Lazarus. If not please reopen the issue and attach the gif image that does not work.
