### ISSUE TITLE
Does KControls support Windows 64-bit target?

### ISSUE THREAD

**Issue by mgtruuuu** [kryslt/KControls#67]
I opened KControls_D12.dproj, set "Windows 64-bit (Modern)" target, and tried to compile but I got this error:

`[dcc64 Fatal Error] KControls_D12.dpk(33): E2202 Required package 'dclstd' not found`

and I found "dslstd" package only located in Win32 directory.

Does KControls support Windows 64-bit target?

**Comment by kryslt** [comment]
There is no problem using KControls in 64bit apps.
KControls_D12 is design time package, it cannot be compiled for Win64 because Delphi itself is still Win32 app. 
But KControls itself can be compiled for 64 bit.
Just open KControls_R12 package, add Win64 platform and it will compile fine.
