### ISSUE TITLE
Strange behavior of TKNumberEdit

### ISSUE THREAD

**Issue by EllaYard** [kryslt/KControls#68]
Hi, I want use  TKNumberEdit component to filter hex numbers in range from 0 to 0x7FFFFFFF or from 0 to 0x7FFFFFFFFFFFFFFF
I opened demo "KControls-master\demos\kicon" and add next code to FormCreate procedure:

  EDPNGThreshold.AcceptedFormats:=[neafHex];
  EDPNGThreshold.ValueAsInt:=8;
  EDPNGThreshold.MaxAsInt:=$7FFFFFFF;

Then i execute demo and start pressing UP button on TKNumberEdit. The i get following results:
0 press: 0x00000008
1 press: 0x00000009
2 press: 0x00100000
3 press: 0x00200000
On second press i expected to get 0x0000000A not 0x00100000

**Comment by EllaYard** [comment]
Also if i change code on FormCreate to:

  EDPNGThreshold.AcceptedFormats:=[neafAscii];
  EDPNGThreshold.ValueAsInt:=8;
  EDPNGThreshold.MaxAsInt:=$7FFFFFFF; <---- the program will freeze at this assign
  
  I use Delphi 11.3

**Comment by kryslt** [comment]
See my fix. 
The first one was not a bug, was correct because of a TUpDown limitation. This limitation is not present in Delphi XE5 and higher anymore so I removed the respective calculation for them. 
The second one was a bug indeed - fixed.

**Comment by EllaYard** [comment]
Thank you for fast fix. 
As I understand, to use this component for numbers bigger then integer i need to modify TUpDown class, because Min and Max are limited to integer values. am I right?

**Comment by kryslt** [comment]
Or disable updown (neoUseUpDown off).

**Comment by kryslt** [comment]
I made another fix for 64bit signed/unsigned display. 
To use 64bit unsigned:
```
  EDPNGThreshold.AcceptedFormats:=[neafHex];
  EDPNGThreshold.Options:=EDPNGThreshold.Options + [neoUnsigned] - [neoUseUpdown];
  EDPNGThreshold.FixedWidth:= 16;
  EDPNGThreshold.MinAsUInt:=  0;
  EDPNGThreshold.MaxAsUInt:=  $FFFFFFFFFFFFFFFF;
  EDPNGThreshold.ValueAsUInt:=$FFFFFFFFFFFFFFFE; // test value
```
To use 64bit signed:
```
  EDPNGThreshold.AcceptedFormats:=[neafHex];
  EDPNGThreshold.Options:=EDPNGThreshold.Options - [neoUseUpdown];
  EDPNGThreshold.FixedWidth:= 16;
  EDPNGThreshold.MinAsInt:=  $8000000000000000;
  EDPNGThreshold.MaxAsInt:=  $7FFFFFFFFFFFFFFF;
  EDPNGThreshold.ValueAsInt:=$7FFFFFFFFFFFFFFE; // test value

```
Note this will not work in very old Delphi versions prior Delphi 2007.
For bigger numbers such as 128bit integers you need another solution.
